

from .age_extraction_json_to_json import extract_age_json
from .education_extraction_json_to_json import extract_education_table
from .first_languageextraction_json_to_json import extract_language_table
from .second_language_json_to_json import extract_second_language_table
from .canadian_work_experience_json_to_json import extract_key_value_table
from .spouse_education_json_to_json import extract_spouse_education_table
from .spouse_language_json_to_json import extract_spouse_language_table
from .spouse_work_json_to_json import extract_spouse_work_table
from .additional_json_to_json import extract_additional_points
from .language_education_json_to_json import extract_language_education_points
from .work_education_json_to_json import extract_canadian_work_edu_points
from .foreign_work_language_json_to_json import extract_foreign_work_language_points
from .foreign_canadian_work_json_to_json import extract_foreign_canadian_work_points
from .certificate_of_qualification_json_to_json import extract_certificate_of_qualification